### ISSUE TITLE
Issue running test data

### ISSUE THREAD

**Issue by BenLRoss** [faylward/viralrecall#18]
Hello,

I tried running the example data with the command `python viralrecall.py -i examples/arm29B.fna -p test_outdir -t 2 -f` in the ViralRecall conda environment and was returned this error message after it ran to completion:

`Traceback (most recent call last):
  File "viralrecall.py", line 733, in <module>
    status = main()
  File "viralrecall.py", line 728, in main
    run_program(input, project, database, window, phagesize, minscore, minhit, evalue, cpus, plotflag, redo, flanking, batch, summary_file, contiglevel)
  File "viralrecall.py", line 655, in run_program
    plt.ylim(minval, numpy.nanmax(df2["rolling"]))
  File "/media/imperator/bross/miniconda3/envs/ViralRecall/lib/python3.5/site-packages/matplotlib/pyplot.py", line 1478, in ylim
    ret = ax.set_ylim(*args, **kwargs)
  File "/media/imperator/bross/miniconda3/envs/ViralRecall/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 3470, in set_ylim
    if bottom == top:
  File "/media/imperator/bross/miniconda3/envs/ViralRecall/lib/python3.5/site-packages/pandas/core/generic.py", line 1576, in __nonzero__
    .format(self.__class__.__name__))
`

Is this an issue regarding the installed versions of matplotlib (3.0.0) and pandas (0.23.4) in the environment?

**Comment by faylward** [comment]
Yes this looks like a matplotlib error- I would try with a different Python version (tested on 3.5.6) and see if it still comes up. If you don't need the plot you could also try removing the -f flag and seeing if it persists.

**Comment by BenLRoss** [comment]
The environment is installed with Python 3.5.6, and we were able to get the run to complete without the `-f` flag. What version of matplotlib was tested?

**Comment by BenLRoss** [comment]
Sorry for the lapse in response, but I was able to get it to run with matplotlib 3.0.3. Thank you!
