### ISSUE TITLE
Facing problem in running Viralrecall

### ISSUE THREAD

**Issue by vmevada102** [faylward/viralrecall#19]
After installing into the Conda environment i am facing following problem,

Traceback (most recent call last):
  File "viralrecall.py", line 733, in <module>
    status = main()
  File "viralrecall.py", line 728, in main
    run_program(input, project, database, window, phagesize, minscore, minhit, evalue, cpus, plotflag, redo, flanking, batch, summary_file, contiglevel)
  File "viralrecall.py", line 401, in run_program
    df = pandas.concat([df, s1], axis=1, sort=True)
TypeError: concat() got an unexpected keyword argument 'sort'

**Comment by faylward** [comment]
Have you tried python 3.5? I think later versions have pandas issues.


Frank

**Comment by vmevada102** [comment]
I hve set the Python 3.5.6 in conda environment as recommended into the installation.

**Comment by faylward** [comment]
And is this error on the test data or new data you are using?

**Comment by vmevada102** [comment]
This error was found on both dataset.

Test data as well as own data

**Comment by vmevada102** [comment]
Kindly help me resolve the issue

**Comment by faylward** [comment]
This appears to be an issue specific to pandas - you will need to troubleshoot the version of pandas you have installed. Please see https://stackoverflow.com/questions/54312781/python3-prophet-model-predict-throws-typeerror-concat-got-an-unexpected-key

**Comment by abdealijivaji** [comment]
I run viralrecall with pandas v1.0.5 because I was running into all sorts of issues with the recent pandas version
