### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by thesamuanels** [faylward/viralrecall#24]
Hello,
I've been trying to run ViralRecall, both using the test provided and with my own data, but it always gives me the following error:

`Traceback (most recent call last):
  File "/opt/viralrecall/viralrecall.py", line 733, in <module>
    status = main()
  File "/opt/viralrecall/viralrecall.py", line 725, in main
    run_program(newinput, newproject, database, window, phagesize, minscore, minhit, evalue, cpus, plotflag, redo, flanking, batch, summary_file, contiglevel)
  File "/opt/viralrecall/viralrecall.py", line 475, in run_program
    summary = summary.append(data)
  File "/opt/Anaconda3/envs/viralrecall/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?`

Any idea what the issue might be?

**Comment by faylward** [comment]
What was your command and input?
I found that many errors can be fixed by playing around with the python
version.

Frank

**Comment by thesamuanels** [comment]
The input for that specific output was: 
`python /opt/viralrecall/viralrecall.py -i test -c -p viralrecall.out -b -e 1e-5`
However, I got the same error when running:
`python viralrecall.py -i examples/arm29B.fna -p test_outdir -t 2 -f`

I have downgraded to python 3.5.6, now when running
`python /opt/viralrecall/viralrecall.py -i test -c -p viralrecall.out -b -e 1e-5`
I've obtained:
     
`Running viralrecall on ALA.Apr2023.130_S8_metabat2.7.fa and output will be deposited in viralrecall.out/`ALA.Apr2023.130_S8_metabat2.7.fa
Traceback (most recent call last):
  File "/opt/viralrecall/viralrecall.py", line 733, in <module>
    status = main()
  File "/opt/viralrecall/viralrecall.py", line 725, in main
    run_program(newinput, newproject, database, window, phagesize, minscore, minhit, evalue, cpus, plotflag, redo, flanking, batch, summary_file, contiglevel)
  File "/opt/viralrecall/viralrecall.py", line 401, in run_program
    df = pandas.concat([df, s1], axis=1, sort=True)
TypeError: concat() got an unexpected keyword argument 'sort'`
And when running

**Comment by faylward** [comment]
Yeah I think this is an issue with the Pandas version then. They changed
the way that data frames can be sorted. So maybe downgrade the pandas
version?
Sorry I can't be more specific.
Frank

**Comment by thesamuanels** [comment]
Solved! Thanks.
We actually had an older version of pandas in our conda environment. It works now with pandas 0.23.0

**Comment by faylward** [comment]
Great! Glad it worked out.

Frank
