### ISSUE TITLE
Can not found the path of database, I have already download this database and put it into the viralrecall category 

### ISSUE THREAD

**Issue by pl19940314** [faylward/viralrecall#29]
Traceback (most recent call last):
  File "/home/meta/mdisk/pl/soil/soil_fasta/test_fasta/viralrecall-master/viralrecall.py", line 735, in <module>
    status = main()
  File "/home/meta/mdisk/pl/soil/soil_fasta/test_fasta/viralrecall-master/viralrecall.py", line 730, in main
    run_program(input, project, database, window, phagesize, minscore, minhit, evalue, cpus, plotflag, redo, flanking, batch, summary_file, contiglevel)
  File "/home/meta/mdisk/pl/soil/soil_fasta/test_fasta/viralrecall-master/viralrecall.py", line 373, in run_program
    raise("Can't seem to find the hmm databases in the hmm/ directory. Please see GitHub for download instructions")
TypeError: exceptions must derive from BaseException

**Comment by faylward** [comment]
Are you in the Viralrecall dorectory when you execute the command? That is
needed.

**Comment by pl19940314** [comment]
Yes, I  put the database into the viralcall directory and built the virtual environment, but it always alarms me the problem, i need put it absoluted path by -db ?

**Comment by faylward** [comment]
As long as you are running the command in that directory , it should find
the database. What is the full command you were using?
